steps:
  - name: gcr.io/cloud-builders/docker
    id: ${_DEPLOYMENT_APPLICATION}
    args:
      - build
      - --tag
      - asia.gcr.io/$PROJECT_ID/${_DEPLOYMENT_APPLICATION}:$TAG_NAME
      - ./application/demo
    waitFor: ["-"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "asia.gcr.io/$PROJECT_ID/${_DEPLOYMENT_APPLICATION}:$TAG_NAME"]
    waitFor:
      - ${_DEPLOYMENT_APPLICATION}

  - name: "gcr.io/cloud-builders/kubectl"
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials ${_CLUSTER_NAME} --zone ${_CLOUDSDK_COMPUTE_ZONE} --project $PROJECT_ID
        kubectl set -n ${_NAMESPACE} image deployment/${_DEPLOYMENT_APPLICATION} ${_DEPLOYMENT_APPLICATION}=asia.gcr.io/$PROJECT_ID/${_DEPLOYMENT_APPLICATION}:$TAG_NAME

substitutions:
  _CLOUDSDK_COMPUTE_ZONE: asia-southeast1-b
  _CLUSTER_NAME: gke-public-1
  _NAMESPACE: demo-production
  _DEPLOYMENT_APPLICATION: demo

timeout: 1800s

options:
  logging: CLOUD_LOGGING_ONLY
